---
# https://docs.ansible.com/ansible/2.9/modules/apt_module.html
- name: Install system packages via apt
  hosts: localhost
  become: true
  tasks:
    - name: Update cache and upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: Clean package repository and remove unused packages
      apt:
        autoclean: yes
        autoremove: yes

    - name: Update all packages
      apt:
        name: "*"
        update_cache: yes
        state: latest

    - name: Install system packages
      apt:
        pkg:
          - cifs-utils
          - curl
          - git
          - git-core
          - kdiff3
          - snapd
          - tree
          - vim
          - zsh
        state: latest
        update_cache: yes

    - name: Install docker packages
      apt:
        pkg:
          - lsb-release
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: latest
        update_cache: yes
